name: Announce a release

on:
  push:
    tags:
      - 'announce-[0-9]+.[0-9]+.[0-9]+'

jobs:
  announce-a-release:
    name: Announce a release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Announce
        uses: ponylang/release-bot-action@0.4.0
        with:
          step: announce-a-release
          GIT_USER_NAME: "Ponylang Main Bot"
          GIT_USER_EMAIL: "ponylang.main@gmail.com"
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          ZULIP_TOKEN: ${{ secrets.ZULIP_TOKEN }}
