name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  x86-64-unknown-linux-release:
    name: Build and upload x86-64-unknown-linux-release to Cloudsmith
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and upload
        run: bash .ci-scripts/release/x86-64-unknown-linux-release.bash
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}

  build-release-docker-images:
    name: Build and push release Docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash .ci-scripts/release/build-docker-images-on-release.bash

  trigger-release-announcement:
    name: Trigger release announcement
    runs-on: ubuntu-latest
    needs: [x86-64-unknown-linux-release, build-release-docker-images]
    steps:
      - uses: actions/checkout@v3
      - name: Trigger
        uses: ponylang/release-bot-action@0.4.0
        with:
          step: trigger-release-announcement
          git_user_name: "Ponylang Main Bot"
          git_user_email: "ponylang.main@gmail.com"
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
